# Define the default platform
# This will be used if no other platform matches
default:
  platform:
    node: "19.8.1"

# Define a platform for Linux x64
linux-x64:
  platform:
    node: "19.8.1"
    os: "linux"
    arch: "x64"

# Define a platform for macOS x64
macos-x64:
  platform:
    node: "19.8.1"
    os: "darwin"
    arch: "x64"

# Define a platform for Windows x64
windows-x64:
  platform:
    node: "19.8.1"
    os: "win32"